// Autogenerated.  Takes 546 bytes of flash.

#ifndef _FACES_H
#define _FACES_H

#include "Animator.hpp"

extern const AnimationSequence eatFace_1;
extern const AnimationSequence eatFace_2;
extern const AnimationSequence eatFace_3;
extern const AnimationSequence eatFace_4;
extern const AnimationSequence satisfiedFace;
extern const AnimationSequence happyFace;
extern const AnimationSequence asleepFace;
extern const AnimationSequence boredFace;
extern const AnimationSequence hungryFace;
extern const AnimationSequence neutralFace;
extern const AnimationSequence sickFace;
extern const AnimationSequence tiredFace;

#endif