// Autogenerated.  Takes 546 bytes of flash.
// NOTE these are declared backwards for linked list purposes

#include "Animator.hpp"
#include "faces.hpp"
#include "images.hpp"
#include "globals.hpp"  // Face size declarations

#pragma region eatFace_1
static const AnimationElement _eatFace_1_hand_id140700601565920 = 
{
 .x = FACE_LEFT + 36,
 .y = 45,
 .w = 16,
 .h = 12,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_hand,
 .next = nullptr
};

static const AnimationElement _eatFace_1_mouth_id140700601566256 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = hungry_mouth,
 .next = &_eatFace_1_hand_id140700601565920
};

static const AnimationElement _eatFace_1_right_eye_id140700601565584 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_right,
 .next = &_eatFace_1_mouth_id140700601566256
};

static const AnimationElement _eatFace_1_left_eye_id140700601566064 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_left,
 .next = &_eatFace_1_right_eye_id140700601565584
};

static const AnimationElement _eatFace_1_base_id140700601565536 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 0,
 .image = base,
 .next = &_eatFace_1_left_eye_id140700601566064
};

const AnimationSequence eatFace_1 = 
{
 .id = 0,
 .head = &_eatFace_1_base_id140700601565536
};
#pragma endregion eatFace_1

#pragma region eatFace_2
static const AnimationElement _eatFace_2_hand_id140700601566160 = 
{
 .x = FACE_LEFT + 29,
 .y = 32,
 .w = 16,
 .h = 12,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_hand,
 .next = nullptr
};

static const AnimationElement _eatFace_2_mouth_id140700601566832 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = hungry_mouth,
 .next = &_eatFace_2_hand_id140700601566160
};

static const AnimationElement _eatFace_2_right_eye_id140700601566544 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_right,
 .next = &_eatFace_2_mouth_id140700601566832
};

static const AnimationElement _eatFace_2_left_eye_id140700601566736 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_left,
 .next = &_eatFace_2_right_eye_id140700601566544
};

static const AnimationElement _eatFace_2_base_id140700601566112 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 0,
 .image = base,
 .next = &_eatFace_2_left_eye_id140700601566736
};

const AnimationSequence eatFace_2 = 
{
 .id = 1,
 .head = &_eatFace_2_base_id140700601566112
};
#pragma endregion eatFace_2

#pragma region eatFace_3
static const AnimationElement _eatFace_3_mouth_id140700601567408 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_mouth_chew_1,
 .next = nullptr
};

static const AnimationElement _eatFace_3_right_eye_id140700601567024 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_right,
 .next = &_eatFace_3_mouth_id140700601567408
};

static const AnimationElement _eatFace_3_left_eye_id140700601567264 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_left,
 .next = &_eatFace_3_right_eye_id140700601567024
};

static const AnimationElement _eatFace_3_base_id140700601566688 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 0,
 .image = base,
 .next = &_eatFace_3_left_eye_id140700601567264
};

const AnimationSequence eatFace_3 = 
{
 .id = 2,
 .head = &_eatFace_3_base_id140700601566688
};
#pragma endregion eatFace_3

#pragma region eatFace_4
static const AnimationElement _eatFace_4_mouth_id140700601567840 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_mouth_chew_2,
 .next = nullptr
};

static const AnimationElement _eatFace_4_right_eye_id140700601567216 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_right,
 .next = &_eatFace_4_mouth_id140700601567840
};

static const AnimationElement _eatFace_4_left_eye_id140700601567648 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_left,
 .next = &_eatFace_4_right_eye_id140700601567216
};

static const AnimationElement _eatFace_4_base_id140700601567168 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 0,
 .image = base,
 .next = &_eatFace_4_left_eye_id140700601567648
};

const AnimationSequence eatFace_4 = 
{
 .id = 3,
 .head = &_eatFace_4_base_id140700601567168
};
#pragma endregion eatFace_4

#pragma region satisfiedFace
static const AnimationElement _satisfiedFace_mouth_id140700601567360 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = satisfied_mouth,
 .next = nullptr
};

static const AnimationElement _satisfiedFace_right_eye_id140700601568176 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = satisfied_eye_right,
 .next = &_satisfiedFace_mouth_id140700601567360
};

static const AnimationElement _satisfiedFace_left_eye_id140700601567696 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = satisfied_eye_left,
 .next = &_satisfiedFace_right_eye_id140700601568176
};

static const AnimationElement _satisfiedFace_base_id140700601567984 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_satisfiedFace_left_eye_id140700601567696
};

const AnimationSequence satisfiedFace = 
{
 .id = 4,
 .head = &_satisfiedFace_base_id140700601567984
};
#pragma endregion satisfiedFace

#pragma region happyFace
static const AnimationElement _happyFace_mouth_id140700601568272 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = happy_mouth,
 .next = nullptr
};

static const AnimationElement _happyFace_right_eye_id140700601568608 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = happy_eye_right,
 .next = &_happyFace_mouth_id140700601568272
};

static const AnimationElement _happyFace_left_eye_id140700601567936 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = happy_eye_left,
 .next = &_happyFace_right_eye_id140700601568608
};

static const AnimationElement _happyFace_base_id140700601568416 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_happyFace_left_eye_id140700601567936
};

const AnimationSequence happyFace = 
{
 .id = 5,
 .head = &_happyFace_base_id140700601568416
};
#pragma endregion happyFace

#pragma region asleepFace
static const AnimationElement _asleepFace_mouth_id140700601568512 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = asleep_mouth,
 .next = nullptr
};

static const AnimationElement _asleepFace_zzzs_id140700601569184 = 
{
 .x = FACE_LEFT + 55,
 .y = FACE_TOP + 7,
 .w = 8,
 .h = 11,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = asleep_zzz,
 .next = &_asleepFace_mouth_id140700601568512
};

static const AnimationElement _asleepFace_right_eye_id140700601568896 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = asleep_eye_right,
 .next = &_asleepFace_zzzs_id140700601569184
};

static const AnimationElement _asleepFace_left_eye_id140700601569088 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = asleep_eye_left,
 .next = &_asleepFace_right_eye_id140700601568896
};

static const AnimationElement _asleepFace_base_id140700601568320 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_asleepFace_left_eye_id140700601569088
};

const AnimationSequence asleepFace = 
{
 .id = 6,
 .head = &_asleepFace_base_id140700601568320
};
#pragma endregion asleepFace

#pragma region boredFace
static const AnimationElement _boredFace_mouth_id140700601569712 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = bored_mouth,
 .next = nullptr
};

static const AnimationElement _boredFace_right_eye_id140700601569328 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = bored_eye_right,
 .next = &_boredFace_mouth_id140700601569712
};

static const AnimationElement _boredFace_left_eye_id140700601569616 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = bored_eye_left,
 .next = &_boredFace_right_eye_id140700601569328
};

static const AnimationElement _boredFace_base_id140700601569040 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_boredFace_left_eye_id140700601569616
};

const AnimationSequence boredFace = 
{
 .id = 7,
 .head = &_boredFace_base_id140700601569040
};
#pragma endregion boredFace

#pragma region hungryFace
static const AnimationElement _hungryFace_mouth_id140700601570144 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = hungry_mouth,
 .next = nullptr
};

static const AnimationElement _hungryFace_right_eye_id140700601569568 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = hungry_eye_right,
 .next = &_hungryFace_mouth_id140700601570144
};

static const AnimationElement _hungryFace_left_eye_id140700601569952 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = hungry_eye_left,
 .next = &_hungryFace_right_eye_id140700601569568
};

static const AnimationElement _hungryFace_base_id140700601569520 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_hungryFace_left_eye_id140700601569952
};

const AnimationSequence hungryFace = 
{
 .id = 8,
 .head = &_hungryFace_base_id140700601569520
};
#pragma endregion hungryFace

#pragma region neutralFace
static const AnimationElement _neutralFace_mouth_id140700601569136 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = neutral_mouth,
 .next = nullptr
};

static const AnimationElement _neutralFace_right_eye_id140700601570480 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = neutral_eye_right,
 .next = &_neutralFace_mouth_id140700601569136
};

static const AnimationElement _neutralFace_left_eye_id140700601570000 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = neutral_eye_left,
 .next = &_neutralFace_right_eye_id140700601570480
};

static const AnimationElement _neutralFace_base_id140700601570288 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_neutralFace_left_eye_id140700601570000
};

const AnimationSequence neutralFace = 
{
 .id = 9,
 .head = &_neutralFace_base_id140700601570288
};
#pragma endregion neutralFace

#pragma region sickFace
static const AnimationElement _sickFace_mouth_id140700601570576 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = sick_mouth,
 .next = nullptr
};

static const AnimationElement _sickFace_right_eye_id140700601570912 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = sick_eye_right,
 .next = &_sickFace_mouth_id140700601570576
};

static const AnimationElement _sickFace_left_eye_id140700601570240 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = sick_eye_left,
 .next = &_sickFace_right_eye_id140700601570912
};

static const AnimationElement _sickFace_base_id140700601570720 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_sickFace_left_eye_id140700601570240
};

const AnimationSequence sickFace = 
{
 .id = 10,
 .head = &_sickFace_base_id140700601570720
};
#pragma endregion sickFace

#pragma region tiredFace
static const AnimationElement _tiredFace_mouth_id140700601570960 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = tired_mouth,
 .next = nullptr
};

static const AnimationElement _tiredFace_right_eye_id140700601571248 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = tired_eye_right,
 .next = &_tiredFace_mouth_id140700601570960
};

static const AnimationElement _tiredFace_left_eye_id140700601568128 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = tired_eye_left,
 .next = &_tiredFace_right_eye_id140700601571248
};

static const AnimationElement _tiredFace_base_id140700601570768 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_tiredFace_left_eye_id140700601568128
};

const AnimationSequence tiredFace = 
{
 .id = 11,
 .head = &_tiredFace_base_id140700601570768
};
#pragma endregion tiredFace

