// Autogenerated.  Takes 546 bytes of flash.
// NOTE these are declared backwards for linked list purposes

#include <avr/pgmspace.h>
#include "faces.h"
#include "Animator.hpp"
#include "images.hpp"
#include "globals.hpp"  // Face size declarations

#pragma region eatFace_1
static const AnimationElement _eatFace_1_hand_id140604991745056 = 
{
 .x = FACE_LEFT + 36,
 .y = 45,
 .w = 16,
 .h = 12,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_hand,
 .next = nullptr
};

static const AnimationElement _eatFace_1_mouth_id140604991745536 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = hungry_mouth,
 .next = &_eatFace_1_hand_id140604991745056
};

static const AnimationElement _eatFace_1_right_eye_id140604991744864 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_right,
 .next = &_eatFace_1_mouth_id140604991745536
};

static const AnimationElement _eatFace_1_left_eye_id140604991745344 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_left,
 .next = &_eatFace_1_right_eye_id140604991744864
};

static const AnimationElement _eatFace_1_base_id140604991743808 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 0,
 .image = base,
 .next = &_eatFace_1_left_eye_id140604991745344
};

const AnimationSequence eatFace_1 = 
{
 .id = 0,
 .head = &_eatFace_1_base_id140604991743808
};
#pragma endregion eatFace_1

#pragma region eatFace_2
static const AnimationElement _eatFace_2_hand_id140604991745968 = 
{
 .x = FACE_LEFT + 29,
 .y = 32,
 .w = 16,
 .h = 12,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_hand,
 .next = nullptr
};

static const AnimationElement _eatFace_2_mouth_id140604991744816 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = hungry_mouth,
 .next = &_eatFace_2_hand_id140604991745968
};

static const AnimationElement _eatFace_2_right_eye_id140604991743760 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_right,
 .next = &_eatFace_2_mouth_id140604991744816
};

static const AnimationElement _eatFace_2_left_eye_id140604991745776 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_left,
 .next = &_eatFace_2_right_eye_id140604991743760
};

static const AnimationElement _eatFace_2_base_id140604991745248 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 0,
 .image = base,
 .next = &_eatFace_2_left_eye_id140604991745776
};

const AnimationSequence eatFace_2 = 
{
 .id = 1,
 .head = &_eatFace_2_base_id140604991745248
};
#pragma endregion eatFace_2

#pragma region eatFace_3
static const AnimationElement _eatFace_3_mouth_id140604991746016 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_mouth_chew_1,
 .next = nullptr
};

static const AnimationElement _eatFace_3_right_eye_id140604991746496 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_right,
 .next = &_eatFace_3_mouth_id140604991746016
};

static const AnimationElement _eatFace_3_left_eye_id140604991745008 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_left,
 .next = &_eatFace_3_right_eye_id140604991746496
};

static const AnimationElement _eatFace_3_base_id140604991746208 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 0,
 .image = base,
 .next = &_eatFace_3_left_eye_id140604991745008
};

const AnimationSequence eatFace_3 = 
{
 .id = 2,
 .head = &_eatFace_3_base_id140604991746208
};
#pragma endregion eatFace_3

#pragma region eatFace_4
static const AnimationElement _eatFace_4_mouth_id140604991746928 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_mouth_chew_2,
 .next = nullptr
};

static const AnimationElement _eatFace_4_right_eye_id140604991746400 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_right,
 .next = &_eatFace_4_mouth_id140604991746928
};

static const AnimationElement _eatFace_4_left_eye_id140604991746736 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = eat_animation_eye_left,
 .next = &_eatFace_4_right_eye_id140604991746400
};

static const AnimationElement _eatFace_4_base_id140604991746352 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DEFAULT,
 .delay = 0,
 .image = base,
 .next = &_eatFace_4_left_eye_id140604991746736
};

const AnimationSequence eatFace_4 = 
{
 .id = 3,
 .head = &_eatFace_4_base_id140604991746352
};
#pragma endregion eatFace_4

#pragma region satisfiedFace
static const AnimationElement _satisfiedFace_mouth_id140604991747360 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = satisfied_mouth,
 .next = nullptr
};

static const AnimationElement _satisfiedFace_right_eye_id140604991746832 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = satisfied_eye_right,
 .next = &_satisfiedFace_mouth_id140604991747360
};

static const AnimationElement _satisfiedFace_left_eye_id140604991747168 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = satisfied_eye_left,
 .next = &_satisfiedFace_right_eye_id140604991746832
};

static const AnimationElement _satisfiedFace_base_id140604991746592 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_satisfiedFace_left_eye_id140604991747168
};

const AnimationSequence satisfiedFace = 
{
 .id = 4,
 .head = &_satisfiedFace_base_id140604991746592
};
#pragma endregion satisfiedFace

#pragma region happyFace
static const AnimationElement _happyFace_mouth_id140604991747408 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = happy_mouth,
 .next = nullptr
};

static const AnimationElement _happyFace_right_eye_id140604991747696 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = happy_eye_right,
 .next = &_happyFace_mouth_id140604991747408
};

static const AnimationElement _happyFace_left_eye_id140604991746160 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = happy_eye_left,
 .next = &_happyFace_right_eye_id140604991747696
};

static const AnimationElement _happyFace_base_id140604991747504 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_happyFace_left_eye_id140604991746160
};

const AnimationSequence happyFace = 
{
 .id = 5,
 .head = &_happyFace_base_id140604991747504
};
#pragma endregion happyFace

#pragma region asleepFace
static const AnimationElement _asleepFace_mouth_id140604991747456 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = asleep_mouth,
 .next = nullptr
};

static const AnimationElement _asleepFace_zzzs_id140604991748272 = 
{
 .x = FACE_LEFT + 55,
 .y = FACE_TOP + 7,
 .w = 8,
 .h = 11,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = asleep_zzz,
 .next = &_asleepFace_mouth_id140604991747456
};

static const AnimationElement _asleepFace_right_eye_id140604991747792 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = asleep_eye_right,
 .next = &_asleepFace_zzzs_id140604991748272
};

static const AnimationElement _asleepFace_left_eye_id140604991748080 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = asleep_eye_left,
 .next = &_asleepFace_right_eye_id140604991747792
};

static const AnimationElement _asleepFace_base_id140604991747072 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_asleepFace_left_eye_id140604991748080
};

const AnimationSequence asleepFace = 
{
 .id = 6,
 .head = &_asleepFace_base_id140604991747072
};
#pragma endregion asleepFace

#pragma region boredFace
static const AnimationElement _boredFace_mouth_id140604991748608 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = bored_mouth,
 .next = nullptr
};

static const AnimationElement _boredFace_right_eye_id140604991748800 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = bored_eye_right,
 .next = &_boredFace_mouth_id140604991748608
};

static const AnimationElement _boredFace_left_eye_id140604991748032 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = bored_eye_left,
 .next = &_boredFace_right_eye_id140604991748800
};

static const AnimationElement _boredFace_base_id140604991748512 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_boredFace_left_eye_id140604991748032
};

const AnimationSequence boredFace = 
{
 .id = 7,
 .head = &_boredFace_base_id140604991748512
};
#pragma endregion boredFace

#pragma region hungryFace
static const AnimationElement _hungryFace_mouth_id140604991749376 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = hungry_mouth,
 .next = nullptr
};

static const AnimationElement _hungryFace_right_eye_id140604991748704 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = hungry_eye_right,
 .next = &_hungryFace_mouth_id140604991749376
};

static const AnimationElement _hungryFace_left_eye_id140604991749184 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = hungry_eye_left,
 .next = &_hungryFace_right_eye_id140604991748704
};

static const AnimationElement _hungryFace_base_id140604991748224 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_hungryFace_left_eye_id140604991749184
};

const AnimationSequence hungryFace = 
{
 .id = 8,
 .head = &_hungryFace_base_id140604991748224
};
#pragma endregion hungryFace

#pragma region neutralFace
static const AnimationElement _neutralFace_mouth_id140604991748992 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = neutral_mouth,
 .next = nullptr
};

static const AnimationElement _neutralFace_right_eye_id140604991749616 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = neutral_eye_right,
 .next = &_neutralFace_mouth_id140604991748992
};

static const AnimationElement _neutralFace_left_eye_id140604991749088 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = neutral_eye_left,
 .next = &_neutralFace_right_eye_id140604991749616
};

static const AnimationElement _neutralFace_base_id140604991749424 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_neutralFace_left_eye_id140604991749088
};

const AnimationSequence neutralFace = 
{
 .id = 9,
 .head = &_neutralFace_base_id140604991749424
};
#pragma endregion neutralFace

#pragma region sickFace
static const AnimationElement _sickFace_mouth_id140604991749568 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = sick_mouth,
 .next = nullptr
};

static const AnimationElement _sickFace_right_eye_id140604991750048 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = sick_eye_right,
 .next = &_sickFace_mouth_id140604991749568
};

static const AnimationElement _sickFace_left_eye_id140604991749520 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = sick_eye_left,
 .next = &_sickFace_right_eye_id140604991750048
};

static const AnimationElement _sickFace_base_id140604991749856 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_sickFace_left_eye_id140604991749520
};

const AnimationSequence sickFace = 
{
 .id = 10,
 .head = &_sickFace_base_id140604991749856
};
#pragma endregion sickFace

#pragma region tiredFace
static const AnimationElement _tiredFace_mouth_id140604990079280 = 
{
 .x = MOUTH_LEFT,
 .y = MOUTH_TOP,
 .w = MOUTH_WIDTH,
 .h = MOUTH_HEIGHT,
 .meta = IMAGE_TRANSPARENT,
 .delay = 0,
 .image = tired_mouth,
 .next = nullptr
};

static const AnimationElement _tiredFace_right_eye_id140604990087920 = 
{
 .x = RIGHT_EYE_LEFT,
 .y = RIGHT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = tired_eye_right,
 .next = &_tiredFace_mouth_id140604990079280
};

static const AnimationElement _tiredFace_left_eye_id140604991749952 = 
{
 .x = LEFT_EYE_LEFT,
 .y = LEFT_EYE_TOP,
 .w = EYE_WIDTH,
 .h = EYE_HEIGHT,
 .meta = IMAGE_TRANSPARENT | IMAGE_DRAWONLY,
 .delay = 0,
 .image = tired_eye_left,
 .next = &_tiredFace_right_eye_id140604990087920
};

static const AnimationElement _tiredFace_base_id140604991748848 = 
{
 .x = FACE_LEFT,
 .y = FACE_TOP,
 .w = FACE_WIDTH,
 .h = FACE_HEIGHT,
 .meta = IMAGE_DRAWONLY,
 .delay = 0,
 .image = base,
 .next = &_tiredFace_left_eye_id140604991749952
};

const AnimationSequence tiredFace = 
{
 .id = 11,
 .head = &_tiredFace_base_id140604991748848
};
#pragma endregion tiredFace

