// Autogenerated.  Takes 7,024 bytes of flash.
#ifndef _IMAGES_H
#define _IMAGES_H

extern uint8_t eatFace_chew2[];
extern uint8_t toilet[];
extern uint8_t base[];
extern uint8_t info[];
extern uint8_t happy[];
extern uint8_t waste[];
extern uint8_t food[];
extern uint8_t eatFace_1[];
extern uint8_t discipline[];
extern uint8_t placeholder[];
extern uint8_t wave[];
extern uint8_t bored[];
extern uint8_t neutral[];
extern uint8_t asleep[];
extern uint8_t apple[];
extern uint8_t light[];
extern uint8_t satisfied[];
extern uint8_t eatFace_chew1[];
extern uint8_t doctor[];
extern uint8_t burger[];
extern uint8_t tired[];
extern uint8_t sick[];
extern uint8_t attention[];
extern uint8_t hungry[];
extern uint8_t play[];

#endif