// Autogenerated.  Takes 2,051 bytes of flash.
#ifndef _IMAGES_H
#define _IMAGES_H

extern uint8_t toilet[];
extern uint8_t base[];
extern uint8_t info[];
extern uint8_t waste[];
extern uint8_t food[];
extern uint8_t discipline[];
extern uint8_t placeholder[];
extern uint8_t wave[];
extern uint8_t apple[];
extern uint8_t light[];
extern uint8_t doctor[];
extern uint8_t burger[];
extern uint8_t attention[];
extern uint8_t play[];
extern uint8_t satisfied_mouth[];
extern uint8_t satisfied_eye_right[];
extern uint8_t satisfied_eye_left[];
extern uint8_t sick_mouth[];
extern uint8_t sick_eye_right[];
extern uint8_t sick_eye_left[];
extern uint8_t happy_eye_left[];
extern uint8_t happy_mouth[];
extern uint8_t happy_eye_right[];
extern uint8_t hungry_mouth[];
extern uint8_t hungry_eye_right[];
extern uint8_t hungry_eye_left[];
extern uint8_t tired_eye_right[];
extern uint8_t tired_mouth[];
extern uint8_t tired_eye_left[];
extern uint8_t asleep_eye_right[];
extern uint8_t asleep_eye_left[];
extern uint8_t asleep_mouth[];
extern uint8_t asleep_zzz[];
extern uint8_t eat_animation_eye_left[];
extern uint8_t eat_animation_eye_right[];
extern uint8_t eat_animation_mouth_chew_2[];
extern uint8_t eat_animation_hand[];
extern uint8_t eat_animation_mouth_chew_1[];
extern uint8_t bored_mouth[];
extern uint8_t bored_eye_left[];
extern uint8_t bored_eye_right[];
extern uint8_t neutral_eye_left[];
extern uint8_t neutral_mouth[];
extern uint8_t neutral_eye_right[];

#endif