// Autogenerated.  Takes 596 bytes of flash.

#ifndef _SEQUENCES_H
#define _SEQUENCES_H

#include "Animator.hpp"

extern const AnimationSequence eatAnimation;
extern const AnimationSequence testAnimation;

#endif